version: '0.1'

services:
  postgres:
    image: postgres
    container_name: rubico
    environment:
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - '5432:5432'
    restart: always

  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
    image: localstack/localstack
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      # s3 서비스만 사용
      - SERVICES=${SERVICES:-s3}
      # 로컬스택 디버그 모드
      - DEBUG=${DEBUG:-0}
      # AWS 계정 정보
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      # AWS 리전
      - AWS_DEFAULT_REGION=ap-northeast-2
    volumes:
      # 로컬스택 볼륨
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      # 도커 소켓 연결
      - '/var/run/docker.sock:/var/run/docker.sock'
      # s3 bucket 생성 스크립트
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/localstack-setup.sh

networks:
  localstack_network:
    driver: bridge
