export const JWT_CONSTANTS = {
  SECRET: 'JWT_SECRET',
  ACCESS_TOKEN_EXPIRES_IN: 'JWT_ACCESS_TOKEN_EXPIRES_IN',
  REFRESH_TOKEN_EXPIRES_IN: 'JWT_REFRESH_TOKEN_EXPIRES_IN',
  ACCESS_TOKEN_IDENTIFY: 'JWT_ACCESS_TOKEN_IDENTIFY',
  REFRESH_TOKEN_IDENTIFY: 'JWT_REFRESH_TOKEN_IDENTIFY',
};
